version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
      - npm install -g serverless
  pre_build:
    commands:
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  build:
    commands:
      - npm run build
      - sls deploy --aws-profile default
  post_build:
    commands:
      - aws s3 sync .output/public s3://nuxt-example-01 --delete
      - aws cloudfront create-invalidation --distribution-id EK0Y81YAK0TW8 --paths "/*"
